#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'abc_size'

path = ARGV[0]
discount = ['-d', '--discount'].include?(ARGV[1])

if path
  AbcSize::Calculator.new.call(path: path, discount: discount)
else
  puts "Usage: abc [file] [options]\n"\
       "\n"\
       "Options:\n"\
       '    -d, --discount    Discount repeated attributes'
end
