#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'abcsize'

path, discount = ARGV

Abcsize::Calculator.new.call(path: path, discount: !discount.nil?)
