#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'abc_size'

path, discount = ARGV

AbcSize::Calculator.new.call(path: path, discount: !discount.nil?)
